package main.java.com.itcom.mapper;

import com.itcom.bean.CheckMoney;

import java.util.List;

public interface CheckMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_money
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int deleteByPrimaryKey(Integer checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_money
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int insert(CheckMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_money
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int insertSelective(CheckMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_money
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    CheckMoney selectByPrimaryKey(Integer checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_money
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int updateByPrimaryKeySelective(CheckMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_money
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int updateByPrimaryKey(CheckMoney record);

    /**
     * 查询用户预约的情况
     * @param checkMoney
     * @return
     */
    List<CheckMoney> selectOrderStatus(CheckMoney checkMoney);

    int updateCheckStatus(CheckMoney checkMoney);

}