package main.java.com.itcom.mapper;

import com.itcom.bean.ParkingLot;

import java.util.List;

public interface ParkingLotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_lot
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int deleteByPrimaryKey(String parkingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_lot
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int insert(ParkingLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_lot
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int insertSelective(ParkingLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_lot
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    ParkingLot selectByPrimaryKey(String parkingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_lot
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int updateByPrimaryKeySelective(ParkingLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_lot
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    int updateByPrimaryKey(ParkingLot record);

    /**
     * 查询停车场的个数
     * @return
     */
    int queryNum();

    List<ParkingLot> selectPark();
}