package main.java.com.itcom.bean;

public class Assess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.assess_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private Integer assessId;


    private String spaceId;

    public String getSpaceId() {
        return spaceId;
    }

    public void setSpaceId(String spaceId) {
        this.spaceId = spaceId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.mark
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.time
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.phone_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String parkingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.content
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.assess_id
     *
     * @return the value of assess.assess_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public Integer getAssessId() {
        return assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.assess_id
     *
     * @param assessId the value for assess.assess_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setAssessId(Integer assessId) {
        this.assessId = assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.mark
     *
     * @return the value of assess.mark
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.mark
     *
     * @param mark the value for assess.mark
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.time
     *
     * @return the value of assess.time
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.time
     *
     * @param time the value for assess.time
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.phone_number
     *
     * @return the value of assess.phone_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.phone_number
     *
     * @param phoneNumber the value for assess.phone_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.parking_id
     *
     * @return the value of assess.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getParkingId() {
        return parkingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.parking_id
     *
     * @param parkingId the value for assess.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setParkingId(String parkingId) {
        this.parkingId = parkingId == null ? null : parkingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.content
     *
     * @return the value of assess.content
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.content
     *
     * @param content the value for assess.content
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}