package main.java.com.itcom.bean;

public class CarSpace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_space.id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_space.space_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private Integer spaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_space.location
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_space.status
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_space.phone_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_space.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String parkingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_space.id
     *
     * @return the value of car_space.id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_space.id
     *
     * @param id the value for car_space.id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_space.space_id
     *
     * @return the value of car_space.space_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_space.space_id
     *
     * @param spaceId the value for car_space.space_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_space.location
     *
     * @return the value of car_space.location
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_space.location
     *
     * @param location the value for car_space.location
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setLocation(String location) {
        this.location = location ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_space.status
     *
     * @return the value of car_space.status
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_space.status
     *
     * @param status the value for car_space.status
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_space.phone_number
     *
     * @return the value of car_space.phone_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_space.phone_number
     *
     * @param phoneNumber the value for car_space.phone_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_space.parking_id
     *
     * @return the value of car_space.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getParkingId() {
        return parkingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_space.parking_id
     *
     * @param parkingId the value for car_space.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setParkingId(String parkingId) {
        this.parkingId = parkingId ;
    }
}