package main.java.com.itcom.bean;

public class ParkingLot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_lot.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String parkingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_lot.name
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_lot.location
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_lot.car_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    private Integer carNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_lot.parking_id
     *
     * @return the value of parking_lot.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getParkingId() {
        return parkingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_lot.parking_id
     *
     * @param parkingId the value for parking_lot.parking_id
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setParkingId(String parkingId) {
        this.parkingId = parkingId == null ? null : parkingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_lot.name
     *
     * @return the value of parking_lot.name
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_lot.name
     *
     * @param name the value for parking_lot.name
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_lot.location
     *
     * @return the value of parking_lot.location
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_lot.location
     *
     * @param location the value for parking_lot.location
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_lot.car_number
     *
     * @return the value of parking_lot.car_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public Integer getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_lot.car_number
     *
     * @param carNumber the value for parking_lot.car_number
     *
     * @mbg.generated Mon Jun 03 16:27:46 CST 2019
     */
    public void setCarNumber(Integer carNumber) {
        this.carNumber = carNumber;
    }
}